// MATH_DATA constant for math formula rendering
export const MATH_DATA: Record<string, string> = {
  mathm10_1: "ABC",
  mathm10_2: "BC^2 = AB^2 + AC^2 + 2AB \\cdot AC \\cdot \\cos A",
  mathm10_3: "BC^2 = AB^2 + AC^2 - 2AB \\cdot AC \\cdot \\cos A",
  mathm10_4: "BC^2 = AB^2 + AC^2 + 2 \\cdot AB \\cdot AC \\cdot \\sin A",
  mathm10_5: "BC^2 = AB^2 + AC^2 - 2 \\cdot AB \\cdot AC \\cdot \\sin A",

  mathm11_1: "AB",
  mathm11_2: "M, N",
  mathm11_3: "AB",
  mathm11_4: "2MA = 3MB",
  mathm11_5: "2\\overrightarrow{MA} = 3\\overrightarrow{MB}",
  mathm11_6: "2\\overrightarrow{MA} = -3\\overrightarrow{MB}",
  mathm11_7: "2 \\overrightarrow{AB} = 3 \\overrightarrow{AM}",
  mathm11_8: "\\overrightarrow{3BM} = \\overrightarrow{BA}",

  mathm12_1: "\\begin{cases}\nx - y \\geq 0 \\\\\nx - y \\leq 2 \\\\\nx + y \\geq 0 \\\\\nx + y \\leq 4\n\\end{cases}",
  mathm12_2: "OABC",
  mathm12_3: "L = 2x + y",

  mathm14_1: "ABCD",
  mathm14_2: "M, N",
  mathm14_3: "AB, CD",
  mathm14_4: "O",
  mathm14_5: "MN",
  mathm14_6: "G",
  mathm14_7: "ABC",
  mathm14_8: "\\overrightarrow{DA} + \\overrightarrow{DB} = 2 \\overrightarrow{DM}",
  mathm14_9: "\\overrightarrow{DA} + \\overrightarrow{DB} + \\overrightarrow{DC} = 2 \\overrightarrow{DO}",
  mathm14_10: "\\overrightarrow{DA} + \\overrightarrow{DB} + \\overrightarrow{DC} = 2 \\overrightarrow{DG}",
  mathm14_11: "\\overrightarrow{DO} = 2 \\overrightarrow{DG}",

  mathm15_1: "ABCD",
  mathm15_2: "O",
  mathm15_3: "AC",
  mathm15_4: "BD",
  mathm15_5: "\\overrightarrow{OA}",
  mathm15_6: "\\overrightarrow{oc}",
  mathm15_7: "\\overrightarrow{OB}",
  mathm15_8: "\\overrightarrow{D0}",
  mathm15_9: "\\overrightarrow{OA} + \\overrightarrow{OC} = \\overrightarrow{OB} + \\overrightarrow{OD}",
  mathm15_10:
    "\\overrightarrow{OA} + \\overrightarrow{OB} + \\overrightarrow{OC} + \\overrightarrow{OD} = \\overrightarrow{AD} + \\overrightarrow{CB}",

  mathm17_1: "ABCD",
  mathm17_2: "AB = 4, AD = 6",
  mathm17_3: "\\vec{u} = \\overline{AB} + \\overline{AC}",

  mathm18_1: "A",
  mathm18_2: "B",
  mathm18_3: "AC",
  mathm18_4: "\\widehat{BAC}, \\widehat{BCA}",
  mathm18_5: "AC = 21   m, \\overline{BAC} = 58^\\circ",
  mathm18_6: "\\overline{BCA} = 80^\\circ",
  mathm18_7: "A",
  mathm18_8: "B",

  mathm19_1: "A",
  mathm19_2: "60°",

  mathm21_1: "A",
  mathm21_2: "0,2   kg",
  mathm21_3: "0,1   kg",
  mathm21_4: "B",
  mathm21_5: "0,2   kg",
  mathm21_6: "0,3   kg",
  mathm21_7: "A",
  mathm21_8: "B",
  mathm21_9: "2   kg",
  mathm21_10: "2   kg",
  mathm21_11: "A",
  mathm21_12: "B",

  mathm2_1: "A",
  mathm2_2: "B",
  mathm2_3: "A \\cap B",
  mathm2_4: "A",
  mathm2_5: "B",
  mathm2_6: "A",
  mathm2_7: "B",
  mathm2_8: "A",
  mathm2_9: "B",
  mathm2_10: "B",
  mathm2_11: "A",

  mathm4_1: "A",
  mathm4_2: "B",
  mathm4_3: "\\varnothing",
  mathm4_4: "A",
  mathm4_5: "B",
  mathm4_6: "A",
  mathm4_7: "B",
  mathm4_8: "B",
  mathm4_9: "A",
  mathm4_10: "A",
  mathm4_11: "B",
  mathm4_12: "A",
  mathm4_13: "B",

  mathm5_1: "\\overrightarrow{a},\\overrightarrow{b}",
  mathm5_2: "k",
  mathm5_3: "k(\\overrightarrow{a} + \\overrightarrow{b}) = k\\overrightarrow{a} + k\\overrightarrow{b}",
  mathm5_4: "\\overrightarrow{a},\\overrightarrow{b}",
  mathm5_5: "k",
  mathm5_6: "k(\\overrightarrow{a} + \\overrightarrow{b}) = k\\overrightarrow{a} + k\\overrightarrow{b}",
  mathm5_7: "\\overrightarrow{a},\\overrightarrow{b}",
  mathm5_8: "k",
  mathm5_9: "k(\\overrightarrow{a} + \\overrightarrow{b}) = k\\overrightarrow{a} + k\\overrightarrow{b}",
  mathm5_10: "\\overrightarrow{a},\\overrightarrow{b}",
  mathm5_11: "k",
  mathm5_12: "k(\\overrightarrow{a} + \\overrightarrow{b}) = k\\overrightarrow{a} + k\\overrightarrow{b}",

  mathm6_1: "\\alpha",
  mathm6_2: "\\sin(90^\\circ - \\alpha) = \\cos \\alpha",
  mathm6_3: "\\sin(90^\\circ - \\alpha) = \\sin \\alpha",
  mathm6_4: "\\sin(90^\\circ - \\alpha) = -\\sin \\alpha",
  mathm6_5: "\\sin(90^\\circ - \\alpha) = -\\cos \\alpha",

  mathm7_1: "\\alpha",
  mathm7_2: "\\cos(180^\\circ - \\alpha) = \\cos \\alpha",
  mathm7_3: "\\cos(180^\\circ - \\alpha) = \\sin \\alpha",
  mathm7_4: "\\cos(180^\\circ - \\alpha) = -\\cos \\alpha",
  mathm7_5: "\\cos(180^\\circ - \\alpha) = -\\sin \\alpha",

  mathm8_1: "G",
  mathm8_2: "\\bigtriangleup ABC",
  mathm8_3: "M",
  mathm8_4: "\\overrightarrow{MA} + \\overrightarrow{MB} + \\overrightarrow{MC} = \\overrightarrow{0}",
  mathm8_5: "\\overrightarrow{MA} + \\overrightarrow{MB} + \\overrightarrow{MC} = \\overrightarrow{MG}",
  mathm8_6: "\\overrightarrow{MA} + \\overrightarrow{MB} + \\overrightarrow{MC} = 2 \\overrightarrow{MG}",
  mathm8_7: "\\overrightarrow{MA} + \\overrightarrow{MB} + \\overrightarrow{MC} = 3MG",

  mathm9_1: "ABC",
  mathm9_2: "R",
  mathm9_3: "\\frac{BC}{\\sin A} = 2R",
  mathm9_4: "\\frac{BC}{\\cos A} = 2R",
  mathm9_5: "\\frac{AB}{\\cos A} = 2R",
  mathm9_6: "\\frac{AB}{\\sin A} = 2R",
};


// Compiled regex for better performance
export const MATH_PLACEHOLDER_REGEX = /\[:\$([^$]+)\$\]|\$((?:\\.|[^$])+)\$/g;
export const HAS_MATH_REGEX = /\[:\$[^$]+\$\]|\$[^$]+\$/;
